"""usuario_id opcional en mensajes_chat

Revision ID: cbb8dcb93f46
Revises: 2a2cadda4a00
Create Date: 2026-09-22 19:21:52.844434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbb8dcb93f46'
down_revision = '2a2cadda4a00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
