"""fase 1 catalogo

Revision ID: cf4c5737091f
Revises: 2a2cadda4a00
Create Date: 2026-10-09 08:32:22.222720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf4c5737091f'
down_revision = 'cbb8dcb93f46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ambito', sa.Enum('ACTIVIDAD', 'DONACION', 'PUBLICACION', name='ambito_categoria', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_categorias_ambito_nombre', 'categorias', ['ambito', sa.text('lower(nombre)')], unique=True)
    op.create_table('ciudades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('estado', sa.String(length=80), nullable=False),
    sa.Column('activa', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('organizaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('verificada', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('whatsapp', sa.String(length=20), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('centros_visiteo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('ASILO', 'CASA_HOGAR', 'COMEDOR', name='tipo_centro', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion_corta', sa.String(length=300), nullable=False),
    sa.Column('informacion_general', sa.Text(), nullable=False),
    sa.Column('direccion', sa.String(length=250), nullable=False),
    sa.Column('ciudad_id', sa.Integer(), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('como_ayudar', sa.Text(), nullable=True),
    sa.Column('recomendaciones', sa.Text(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('whatsapp', sa.String(length=20), nullable=True),
    sa.Column('verificado', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['ciudad_id'], ['ciudades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_centros_visiteo_ciudad_id'), 'centros_visiteo', ['ciudad_id'], unique=False)
    op.create_table('iniciativas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('ACTIVIDAD', 'PROYECTO', 'DONACION', name='tipo_iniciativa', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('titulo', sa.String(length=160), nullable=False),
    sa.Column('descripcion_corta', sa.String(length=300), nullable=False),
    sa.Column('ubicacion', sa.String(length=200), nullable=True),
    sa.Column('ciudad_id', sa.Integer(), nullable=False),
    sa.Column('organizacion_id', sa.UUID(), nullable=True),
    sa.Column('activa', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('creado_por', sa.UUID(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ciudad_id'], ['ciudades.id'], ),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_iniciativas_ciudad_tipo_activa', 'iniciativas', ['ciudad_id', 'tipo', 'activa'], unique=False)
    op.create_table('actividades',
    sa.Column('iniciativa_id', sa.UUID(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('inicia_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('termina_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cupo_total', sa.Integer(), nullable=False),
    sa.Column('acerca_de', sa.Text(), nullable=True),
    sa.CheckConstraint('cupo_total > 0', name='ck_actividades_cupo_positivo'),
    sa.CheckConstraint('termina_en > inicia_en', name='ck_actividades_fechas'),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['iniciativa_id'], ['iniciativas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('iniciativa_id')
    )
    op.create_index(op.f('ix_actividades_inicia_en'), 'actividades', ['inicia_en'], unique=False)
    op.create_table('centro_necesidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('centro_id', sa.UUID(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('orden', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['centro_id'], ['centros_visiteo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_centro_necesidades_centro_id'), 'centro_necesidades', ['centro_id'], unique=False)
    op.create_table('donaciones',
    sa.Column('iniciativa_id', sa.UUID(), nullable=False),
    sa.Column('modalidad', sa.Enum('CAMPANA', 'ESPECIE', name='modalidad_donacion', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('meta', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('descripcion_larga', sa.Text(), nullable=True),
    sa.Column('whatsapp', sa.String(length=20), nullable=True),
    sa.Column('condiciones_recepcion', sa.Text(), nullable=True),
    sa.CheckConstraint('meta IS NULL OR meta >= 0', name='ck_donaciones_meta_no_negativa'),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['iniciativa_id'], ['iniciativas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('iniciativa_id')
    )
    op.create_table('iniciativa_imagenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iniciativa_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('orden', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['iniciativa_id'], ['iniciativas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iniciativa_imagenes_iniciativa_id'), 'iniciativa_imagenes', ['iniciativa_id'], unique=False)
    op.create_table('proyectos',
    sa.Column('iniciativa_id', sa.UUID(), nullable=False),
    sa.Column('estado', sa.Enum('ACTIVO', 'ANTERIOR', name='estado_proyecto', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('beneficiarios', sa.String(length=120), nullable=False),
    sa.Column('acerca_de', sa.Text(), nullable=True),
    sa.Column('descripcion_larga', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('whatsapp', sa.String(length=20), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['iniciativa_id'], ['iniciativas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('iniciativa_id')
    )
    op.create_table('donacion_etiquetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donacion_id', sa.UUID(), nullable=False),
    sa.Column('grupo', sa.Enum('ARTICULO', 'DESTINATARIO', 'CONDICION', 'METODO_ENTREGA', name='grupo_etiqueta', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('valor', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['donacion_id'], ['donaciones.iniciativa_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('donacion_id', 'grupo', 'valor', name='uq_donacion_etiqueta')
    )
    op.create_index(op.f('ix_donacion_etiquetas_donacion_id'), 'donacion_etiquetas', ['donacion_id'], unique=False)
    op.create_table('donacion_opciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donacion_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=160), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['donacion_id'], ['donaciones.iniciativa_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donacion_opciones_donacion_id'), 'donacion_opciones', ['donacion_id'], unique=False)
    op.create_table('proyecto_opciones_apoyo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('TIEMPO_TALENTO', 'APORTACION_ECONOMICA', 'MATERIAL', name='tipo_apoyo', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.iniciativa_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proyecto_opciones_apoyo_proyecto_id'), 'proyecto_opciones_apoyo', ['proyecto_id'], unique=False)
    op.create_index('ix_mensajes_chat_usuario_creado', 'mensajes_chat', ['usuario_id', 'creado_en'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mensajes_chat_usuario_creado', table_name='mensajes_chat')
    op.drop_index(op.f('ix_proyecto_opciones_apoyo_proyecto_id'), table_name='proyecto_opciones_apoyo')
    op.drop_table('proyecto_opciones_apoyo')
    op.drop_index(op.f('ix_donacion_opciones_donacion_id'), table_name='donacion_opciones')
    op.drop_table('donacion_opciones')
    op.drop_index(op.f('ix_donacion_etiquetas_donacion_id'), table_name='donacion_etiquetas')
    op.drop_table('donacion_etiquetas')
    op.drop_table('proyectos')
    op.drop_index(op.f('ix_iniciativa_imagenes_iniciativa_id'), table_name='iniciativa_imagenes')
    op.drop_table('iniciativa_imagenes')
    op.drop_table('donaciones')
    op.drop_index(op.f('ix_centro_necesidades_centro_id'), table_name='centro_necesidades')
    op.drop_table('centro_necesidades')
    op.drop_index(op.f('ix_actividades_inicia_en'), table_name='actividades')
    op.drop_table('actividades')
    op.drop_index('ix_iniciativas_ciudad_tipo_activa', table_name='iniciativas')
    op.drop_table('iniciativas')
    op.drop_index(op.f('ix_centros_visiteo_ciudad_id'), table_name='centros_visiteo')
    op.drop_table('centros_visiteo')
    op.drop_table('organizaciones')
    op.drop_table('ciudades')
    op.drop_index('uq_categorias_ambito_nombre', table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
